version: '3.7'
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - network
    volumes:
      - C:\Users\akqjs2002\Desktop\파이썬 프로젝트\20221008 보관용\오삼지하수\nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/statc
      - media-volume:/data/media

    ports:
      - "80:80"

    depends_on:
      - django


  groundwater:
    image: django:groundwater
    networks:
      - network
    volumes:
      - static-volume:/home/ground_water/staticfiles
      - media-volume:/home/ground_water/media


networks:
  network:

volumes:
  static-volume:
  media-volume:
  
